apiVersion: v2
name: nexus-repository
version: 1.0.0
appVersion: 3.22.0
description: Sonatype Nexus is an open source repository manager
keywords:
  - artifacts
  - dependency
  - management
  - sonatype
  - nexus
  - repository
home: https://www.sonatype.com/nexus-repository-oss
icon: http://www.sonatype.org/nexus/content/uploads/2015/06/Nexus-Logo.jpg
sources:
  - https://github.com/sonatype/nexus-public
  - https://github.com/travelaudience/docker-nexus
  - https://github.com/travelaudience/kubernetes-nexus
maintainers:
  - name: justin-coveros
    email: justin.hollingsworth@coveros.com
