{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexus-repository.fullname" . }}
  labels:
    {{- include "nexus-repository.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.secret.data | nindent 2 }}
{{- end}}
